### PR TITLE
Use any version of Python 3 instead of just 3.2

### PR DESCRIPTION
**Pull request by jstaf**

### CODE REVIEW

**Comment by impredicative** [comment]
Thank you. There also some other places in the code where I now replaced python3.2 with python3. The main reason why I have not updated this program is because I don't have access to a GPFS instance anymore!

**Comment by jstaf** [comment]
No worries! You'll probably be pleased to know that this software still works perfectly on GPFS 4.2 (haven't tested it on v5 yet) and CentOS 7.

**Comment by impredicative** [comment]
@jstaf Good to know. Is that with Python 3.6? Which version of Python was used? `python3 -V` should say.

**Comment by jstaf** [comment]
```
$ python3 --version
Python 3.6.3 :: Anaconda custom (64-bit)
```

(It also works on 3.4, and 3.5)

**Pull request merged**
